export const S = {
  view: "login",
  authReady: false,
  user: null,
  groups: [],
  activeGroup: null,
  runs: [],
  allMembers: [],
  tab: "week",
  weekOffset: 0,
  appTab: "agenda",
  form: { date: "", time: "", location: "", distance: "", duration: "", elevation: "", run_type: "", terrain: "", flexible: false, desc: "" },
  modal: null,
  showForm: false,
  authMode: "signin",
};
